Lesson1
marypershai/react-notes-app pull request #1
Opened 2023-11-18 11:32 UTC by marypershai

1. Task: https://docs.google.com/document/d/1VgUifkfM7kk3uq-T9UPQVRJcZwrFoHTaTw111IC5fiY/edit
2. Screenshot: 
![image](https://github.com/marypershai/react-notes-app/assets/54803516/ad26fa6d-4d7f-4da9-9759-bd71a071c334)

3. Done 20.11.2023 / deadline 20.11.2023

2023-11-20 19:13 UTC, tagizade-samir requested changes

2023-11-20 19:13 UTC, tagizade-samir commented on src/components/inputField/InputField.tsx
> +          onClick={(event: React.MouseEvent<HTMLAnchorElement>) => viewPassword(event)}></a>
Если ты просто прокидываешь event дальше, то можно сделать так
onClick={viewPassword}

2023-11-20 20:32 UTC, Strifusha commented on src/main.tsx
>  ReactDOM.createRoot(document.getElementById('root')!).render(
Approve!

2023-11-21 05:40 UTC, marypershai commented on src/components/inputField/InputField.tsx
> +          onClick={(event: React.MouseEvent<HTMLAnchorElement>) => viewPassword(event)}></a>
спасибо! не знала что так можно
исправила

2023-11-21 05:42 UTC, marypershai commented on src/main.tsx
>  ReactDOM.createRoot(document.getElementById('root')!).render(
А поставь пжл палец в правом верхнем углу в секции Reviewers :)
![image](https://github.com/marypershai/react-notes-app/assets/54803516/bb23b59d-8b0a-4398-a1c9-f169a3eea0f9)

2023-11-21 08:03 UTC, tagizade-samir approved these changes

2023-11-21 08:33 UTC, Strifusha approved these changes

2023-11-21 08:33 UTC, Strifusha commented
Great!

2023-11-21 08:34 UTC, merged