Lesson5
marypershai/react-notes-app pull request #5
Opened 2023-12-03 18:04 UTC by marypershai

1. Task: https://docs.google.com/document/d/10uhwFWVSpR-EnWM_ut9kigomT8ouS-2qi5LLHHlFVP0/edit
2. Screenshot: 
3. Done 4.12.2023 / deadline 4.12.2023
4. Checks:
!! Некоторый функционал отвалился\не сделан по причине нехватки запросов и требований как должно работать
- [x] Add Redux
- [x] Configure Redux store
      -     Create a store
      -     Add user, personal notes and public notes reducers
      -     Add respective selectors
- [x] Use values from store
    Replace some local use state or context values with values from Redux

Login creds:
{
        "password": "Maryia2023!",
        "username": "Maryia"
}

2023-12-04 17:35 UTC, tagizade-samir requested changes

2023-12-04 17:35 UTC, tagizade-samir commented on src/pages/authorizationPage/loginPage/LoginPage.tsx
> +    dispatch(authSlice.actions.authChangeErrorState());
Здесь предлагаю лучше экспортировать action-ы из файла, где ты хранишь slice. В твоем случае ты сейчас импортируешь весь slice в каждый свой компонент, что не совем желательно делать
В файле slice можешь сделать
export const {authChangeErrorState} = authSlice.action
Посмотри вот тут пожалуйста - https://redux-toolkit.js.org/api/createSlice

2023-12-05 10:23 UTC, marypershai commented on src/pages/authorizationPage/loginPage/LoginPage.tsx
> +    dispatch(authSlice.actions.authChangeErrorState());
Исправила, но возник вопрос
![image](https://github.com/marypershai/react-notes-app/assets/54803516/82577316-6091-49d3-9c5a-93247e00a793)
В некоторых action есть параметры и первый это стейт, но его мы же не передаем через вызов в dispatcher, вот как это правильно описать

2023-12-05 19:50 UTC, tagizade-samir commented on src/pages/authorizationPage/loginPage/LoginPage.tsx
> +    dispatch(authSlice.actions.authChangeErrorState());
Интересно, я стянул твой код и у меня эта часть показывается без ошибок
![image](https://github.com/marypershai/react-notes-app/assets/50668309/30313c97-4deb-4278-a969-30d136b9fad9)

2023-12-05 19:50 UTC, tagizade-samir commented on src/pages/authorizationPage/loginPage/LoginPage.tsx
> +    dispatch(authSlice.actions.authChangeErrorState());
Потому что по идее эти action-ы, не смотря на то, что внутри slice-а принимают 2 аргумента, при вызове принимают только один

2023-12-06 07:26 UTC, tagizade-samir approved these changes

2023-12-06 07:26 UTC, merged